/**
 * SmartTransit OS — Centralized Shared Entity Constants
 * Sourced canonically from the regional transit dataset (maharashtra_transit_analysis.csv).
 */

export const SHARED_ENTITIES = {
  PRIMARY_BUS: {
    id: 'reg-bus-1',
    busNumber: 'BEST A-297',
    rawBusNumber: 'A-297',
    operator: 'BEST',
    serial: 'REG-BEST-A297',
    routeId: 'BEST-A297',
    routeName: 'BEST A-297 (Borivali Station (E) ➔ Kokanipada Ext)',
    driverId: 'PILOT-BEST-01',
    driverName: 'BEST Division Pilot',
    depot: 'BEST Regional Depot (Borivali East)',
    origin: 'Borivali Station (E)',
    destination: 'Kokanipada Ext',
    currentLocation: 'Borivali Station (E)',
    nextStop: 'Kokanipada Ext',
    area: 'Borivali (East)',
    region: 'Mumbai Suburban',
  },
  AIRPORT_BUS: {
    id: 'reg-bus-25',
    busNumber: 'MSRTC Shivneri',
    rawBusNumber: 'Shivneri',
    operator: 'MSRTC',
    serial: 'REG-MSRTC-Shivneri',
    routeId: 'MSRTC-Shivneri',
    routeName: 'MSRTC Shivneri (Dadar (East) / Nancy Colony ➔ Pune Station / Swargate)',
    driverId: 'PILOT-MSRTC-01',
    driverName: 'MSRTC Intercity Pilot',
    depot: 'MSRTC Central Stand (Dadar)',
    origin: 'Dadar (East) / Nancy Colony',
    destination: 'Pune Station / Swargate',
    currentLocation: 'Dadar (East) / Nancy Colony',
    nextStop: 'Pune Station / Swargate',
    area: 'Mumbai/Pune',
    region: 'Intercity Maharashtra',
  },
  CBD_BUS: {
    id: 'reg-bus-19',
    busNumber: 'NMMT 100',
    rawBusNumber: '100',
    operator: 'NMMT',
    serial: 'REG-NMMT-100',
    routeId: 'NMMT-100',
    routeName: 'NMMT 100 (CBD Belapur ➔ Lokmanya Tilak Terminus (LTT))',
    driverId: 'PILOT-NMMT-01',
    driverName: 'NMMT Division Pilot',
    depot: 'NMMT Depot (CBD Belapur)',
    origin: 'CBD Belapur',
    destination: 'Lokmanya Tilak Terminus (LTT)',
    currentLocation: 'CBD Belapur',
    nextStop: 'Lokmanya Tilak Terminus (LTT)',
    area: 'Belapur',
    region: 'Navi Mumbai / Mumbai',
  },
  EXPRESS_BUS: {
    id: 'reg-bus-12',
    busNumber: 'TMT AC-65',
    rawBusNumber: 'AC-65',
    operator: 'TMT',
    serial: 'REG-TMT-AC65',
    routeId: 'TMT-AC65',
    routeName: 'TMT AC-65 (Thane Station (E) ➔ Borivali Station (E))',
    driverId: 'PILOT-TMT-01',
    driverName: 'TMT Division Pilot',
    depot: 'TMT Central Depot (Thane)',
    origin: 'Thane Station (E)',
    destination: 'Borivali Station (E)',
    currentLocation: 'Thane Station (E)',
    nextStop: 'Borivali Station (E)',
    area: 'Thane',
    region: 'Thane / Mumbai',
  },
};

export default SHARED_ENTITIES;
